---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  selector:
    app: jenkins
    environment: production
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32555
