---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
    - image: alpine
      name: alpine-container
      args:
       - /bin/sh
       - -c
       - sleep 1d
      envFrom:
        - secretRef:
            name: first-secret
