---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/log
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
