---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-pv
spec:
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /var/log
  persistentVolumeReclaimPolicy: Retain
  volumeMode: FileSystem
