---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
    - image: alpine
      name: alpine-container
      args:
       - /bin/sh
       - -c
       - sleep 1d
      envFrom:
        - configMapRef:
            name: appconfigmap
            
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-vol-demo
spec:
  containers:
    - image: alpine
      name: alpine-container
      args:
       - /bin/sh
       - -c
       - sleep 1d
      volumeMounts:
        - name: config-volume
          mountPath: /etc/appconfig
  volumes:
    - name: config-volume
      configMap:
        name: appconfigmap
